### ISSUE TITLE
Species Alert signup causing new warehouse account if email is not exact case match

### ISSUE THREAD

**Issue by andrewvanbreda** [Indicia-Team/warehouse#231] opened 2016-11-16 14:01 UTC
Situation
I ask a user to create an iRecord account so that when species alerts settings are created for them they can be administered on their My Account page.

The user is then signed up to species alerts by me using the invasive alert sign-up page on CEDaR which points to
http://www.brc.ac.uk/irecord/species-alert-notifications

At the point I sign them up, I am not logged into iRecord, so am able to sign them up using their name, email address on this page.
I then look on iRecord and see they are not listed as having alerts on their account.

I find what has happened is the system has created a separate warehouse account because the although I used their email address for sign-up, they had used capital letters when they signed up to iRecord and I hadn't signing up to species alerts.
Email address check prob shouldn't be case sensitive and a new account probably shouldn't have been created

**Comment by JimBacon** [comment] 2016-11-16 14:04
Duplicate of https://github.com/Indicia-Team/warehouse/issues/151?

**Comment by andrewvanbreda** [comment] 2016-11-16 14:21
Granted, although I would like to leave this one open so this exact scenario can be checked once the other one is fixed

**Comment by johnvanbreda** [comment] 2019-04-04 13:36
Fixed - https://github.com/Indicia-Team/warehouse/commit/bf10670a010aba21b0295a7cea2f9167c1048941

**Closed by johnvanbreda** 2019-04-04 13:36 UTC
